import type { GenerateResult, GeneratedDocument } from './generate.js';
import { findGaps, sortGaps, complianceScore, type ComplianceAnswer, type Gap } from './types.js';

/**
 * Export formats.
 *
 * Three, because three is what people actually need:
 *
 *  - **markdown** — the working format, diffable, readable in a PR;
 *  - **json** — for the dashboard and for re-rendering;
 *  - **docx** — for the lawyer or accountant who will not open a .md file.
 *
 * DOCX is emitted as a minimal OOXML package rather than through a document
 * library: a compliance pack is plain paragraphs and tables, and a 200 kB
 * dependency that renders headings differently from Word is not worth it. The
 * output opens in Word, LibreOffice and Google Docs.
 */
export type ExportFormat = 'md' | 'markdown' | 'json' | 'docx';

export interface BundleFile {
  /** Path relative to the output directory. */
  path: string;
  content: string | Uint8Array;
  kind: 'markdown' | 'json' | 'document';
  title: string;
  framework: string;
}

export interface BundleResult {
  format: ExportFormat;
  files: BundleFile[];
  /** The manifest describing what was generated and what is missing. */
  manifest: BundleManifest;
}

export interface BundleManifest {
  company: string;
  system: string;
  generatedAt: string;
  frameworks: string[];
  documentCount: number;
  gapCount: number;
  blockers: number;
  score: number;
  gaps: Gap[];
  documents: { id: string; title: string; reference: string; path: string; unresolved: string[] }[];
  disclaimer: string;
}

const DISCLAIMER =
  'Generated by ShipReady from a self-assessment. These documents are a starting point for your compliance work, not legal advice, not a conformity assessment, and not a substitute for professional review. Verify every statement against your actual operations before relying on it.';

/** Build the manifest describing a generated pack. */
export function buildManifest(answer: ComplianceAnswer, result: GenerateResult): BundleManifest {
  const gaps = result.gaps.length > 0 ? result.gaps : sortGaps(findGaps(answer));
  return {
    company: answer.company.legalName,
    system: answer.aiSystem.name,
    generatedAt: result.generatedAt,
    frameworks: result.frameworks,
    documentCount: result.documents.length,
    gapCount: gaps.length,
    blockers: gaps.filter((g) => g.severity === 'blocker').length,
    score: result.score > 0 ? result.score : complianceScore(gaps),
    gaps,
    documents: result.documents.map((doc) => ({
      id: doc.id,
      title: doc.title,
      reference: doc.reference,
      path: doc.id.replace('/', '/') + '.md',
      unresolved: doc.unresolved,
    })),
    disclaimer: DISCLAIMER,
  };
}

/** One markdown file per document, plus a manifest and a README index. */
export function toMarkdownBundle(result: GenerateResult, manifest: BundleManifest): BundleResult {
  const files: BundleFile[] = [];

  for (const document of result.documents) {
    files.push({
      path: `${document.framework}/${document.id.split('/')[1] ?? document.id}.md`,
      content: withHeader(document),
      kind: 'markdown',
      title: document.title,
      framework: document.framework,
    });
  }

  files.push({
    path: 'MANIFEST.md',
    content: renderManifestMarkdown(manifest),
    kind: 'markdown',
    title: 'Compliance manifest',
    framework: 'all',
  });

  files.push({
    path: 'README.md',
    content: renderIndexMarkdown(manifest, result.documents),
    kind: 'markdown',
    title: 'Compliance pack index',
    framework: 'all',
  });

  return { format: 'md', files, manifest };
}

/** A single JSON document containing everything. */
export function toJsonBundle(result: GenerateResult, manifest: BundleManifest): BundleResult {
  const content = JSON.stringify(
    {
      manifest,
      documents: result.documents.map((d) => ({
        id: d.id,
        framework: d.framework,
        title: d.title,
        reference: d.reference,
        markdown: d.content,
        gaps: d.gaps,
        unresolvedPlaceholders: d.unresolved,
      })),
    },
    null,
    2,
  );
  return {
    format: 'json',
    files: [{ path: 'compliance-pack.json', content, kind: 'json', title: 'Compliance pack', framework: 'all' }],
    manifest,
  };
}

/**
 * DOCX bundle: one document containing every section.
 *
 * Word supports a multi-page document far better than it supports opening many
 * files, so the pack ships as a single `.docx` with a table of contents field.
 */
export function toDocxBundle(result: GenerateResult, manifest: BundleManifest): BundleResult {
  const body = renderDocxBody(result.documents, manifest);
  return {
    format: 'docx',
    files: [
      { path: 'compliance-pack.docx', content: buildDocx(body), kind: 'document', title: 'Compliance pack', framework: 'all' },
    ],
    manifest,
  };
}

// ---------------------------------------------------------------------------
// Markdown rendering
// ---------------------------------------------------------------------------

function withHeader(document: GeneratedDocument): string {
  return [
    `<!-- Framework: ${document.framework} -->`,
    `<!-- Reference: ${document.reference} -->`,
    `<!-- Gaps affecting this document: ${document.gaps.length} -->`,
    '',
    document.content,
  ].join('\n');
}

function renderManifestMarkdown(manifest: BundleManifest): string {
  const lines: string[] = [];
  lines.push('# Compliance manifest');
  lines.push('');
  lines.push(`**Company:** ${manifest.company}`);
  lines.push(`**System:** ${manifest.system}`);
  lines.push(`**Generated:** ${manifest.generatedAt}`);
  lines.push(`**Readiness score:** ${manifest.score}/100`);
  lines.push('');
  lines.push(`This pack contains ${manifest.documentCount} documents across ${manifest.frameworks.join(', ')}.`);
  lines.push('');

  lines.push('## Documents');
  lines.push('');
  lines.push('| Document | Reference | Unresolved placeholders |');
  lines.push('| --- | --- | --- |');
  for (const doc of manifest.documents) {
    lines.push(`| ${doc.title} | ${doc.reference} | ${doc.unresolved.length === 0 ? 'none' : doc.unresolved.length} |`);
  }
  lines.push('');

  lines.push('## Gaps');
  lines.push('');
  if (manifest.gaps.length === 0) {
    lines.push('No gaps were identified from the answers provided.');
  } else {
    lines.push('| Severity | Missing | Why it matters |');
    lines.push('| --- | --- | --- |');
    for (const gap of manifest.gaps) {
      lines.push(`| ${gap.severity.toUpperCase()} | ${escapeCell(gap.message)} | ${escapeCell(gap.why)} |`);
    }
  }
  lines.push('');
  lines.push('## Disclaimer');
  lines.push('');
  lines.push(manifest.disclaimer);
  lines.push('');
  return lines.join('\n');
}

function renderIndexMarkdown(manifest: BundleManifest, documents: readonly GeneratedDocument[]): string {
  const lines: string[] = [];
  lines.push(`# ${manifest.company} — compliance pack`);
  lines.push('');
  lines.push(`System: **${manifest.system}**  |  Generated: ${manifest.generatedAt}  |  Readiness: **${manifest.score}/100**`);
  lines.push('');
  lines.push('## What is in here');
  lines.push('');
  for (const framework of manifest.frameworks) {
    lines.push(`### ${framework.toUpperCase()}`);
    lines.push('');
    for (const document of documents.filter((d) => d.framework === framework)) {
      const gapCount = document.gaps.length;
      lines.push(
        `- [${document.title}](./${framework}/${document.id.split('/')[1] ?? document.id}.md) — ${document.reference}${gapCount > 0 ? ` · **${gapCount} gap(s)**` : ''}`,
      );
    }
    lines.push('');
  }

  if (manifest.blockers > 0) {
    lines.push('---');
    lines.push('');
    lines.push(`> **${manifest.blockers} blocker(s) before launch.** See [MANIFEST.md](./MANIFEST.md).`);
    lines.push('');
  }

  lines.push('## How to use this pack');
  lines.push('');
  lines.push('1. Read `MANIFEST.md` first. It lists what is missing and why it matters.');
  lines.push('2. Work the blockers, in order. A blocker means the document is not merely incomplete.');
  lines.push('3. Fill every `**NOT PROVIDED**` marker. Each one is a question a regulator can ask.');
  lines.push('4. Have a qualified person review before relying on any of it.');
  lines.push('');
  lines.push(manifest.disclaimer);
  lines.push('');
  return lines.join('\n');
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

// ---------------------------------------------------------------------------
// DOCX
// ---------------------------------------------------------------------------

/**
 * Minimal OOXML document.
 *
 * A .docx is a zip containing `[Content_Types].xml`, a relationships part,
 * `word/document.xml` and `word/styles.xml`. We emit exactly those, with a
 * heading style set so Word's navigation pane works.
 */
function renderDocxBody(documents: readonly GeneratedDocument[], manifest: BundleManifest): DocxBlock[] {
  const blocks: DocxBlock[] = [];

  blocks.push({ kind: 'title', text: `${manifest.company} — Compliance Documentation Pack` });
  blocks.push({ kind: 'subtitle', text: `System: ${manifest.system}` });
  blocks.push({ kind: 'subtitle', text: `Generated: ${manifest.generatedAt}` });
  blocks.push({ kind: 'subtitle', text: `Readiness score: ${manifest.score}/100` });

  blocks.push({ kind: 'heading', level: 1, text: 'Contents' });
  for (const document of documents) {
    blocks.push({ kind: 'paragraph', text: `${document.title} — ${document.reference}` });
  }

  for (const document of documents) {
    blocks.push({ kind: 'pageBreak' });
    blocks.push({ kind: 'heading', level: 1, text: document.title });
    blocks.push({ kind: 'subtitle', text: document.reference });
    blocks.push({ kind: 'spacer' });
    for (const block of parseMarkdownBlocks(document.content)) blocks.push(block);
  }

  blocks.push({ kind: 'pageBreak' });
  blocks.push({ kind: 'heading', level: 1, text: 'Gaps' });
  for (const gap of manifest.gaps) {
    blocks.push({ kind: 'paragraph', text: `[${gap.severity.toUpperCase()}] ${gap.message} — ${gap.why}` });
    blocks.push({ kind: 'paragraph', text: `    Action: ${gap.action}` });
  }

  blocks.push({ kind: 'pageBreak' });
  blocks.push({ kind: 'heading', level: 1, text: 'Disclaimer' });
  blocks.push({ kind: 'paragraph', text: manifest.disclaimer });

  return blocks;
}

type DocxBlock =
  | { kind: 'title'; text: string }
  | { kind: 'subtitle'; text: string }
  | { kind: 'heading'; level: 1 | 2 | 3; text: string }
  | { kind: 'paragraph'; text: string }
  | { kind: 'bullet'; text: string }
  | { kind: 'spacer' }
  | { kind: 'pageBreak' };

/** Very small markdown subset: headings, bullets, paragraphs, tables as text. */
function parseMarkdownBlocks(markdown: string): DocxBlock[] {
  const blocks: DocxBlock[] = [];
  let inTable = false;

  for (const raw of markdown.split(/\r?\n/)) {
    const line = raw.replace(/\s+$/, '');
    if (line.trim() === '') continue;
    if (line.trimStart().startsWith('<!--')) continue;

    if (line.trimStart().startsWith('|')) {
      // Skip the separator row; render other rows as tab-separated text.
      if (/^\|[\s|:-]+\|$/.test(line.trim())) continue;
      const cells = line.split('|').slice(1, -1).map((c) => c.trim()).filter(Boolean);
      if (cells.length === 0) continue;
      if (!inTable) {
        blocks.push({ kind: 'spacer' });
        inTable = true;
      }
      blocks.push({ kind: 'paragraph', text: cells.join('  ·  ') });
      continue;
    }
    if (inTable) {
      inTable = false;
      blocks.push({ kind: 'spacer' });
    }

    const heading = /^(#{1,6})\s+(.*)$/.exec(line.trim());
    if (heading) {
      const level = Math.min(3, heading[1]!.length) as 1 | 2 | 3;
      blocks.push({ kind: 'heading', level, text: stripInline(heading[2]!) });
      continue;
    }

    const bullet = /^\s*[-*]\s+(.*)$/.exec(line);
    if (bullet) {
      blocks.push({ kind: 'bullet', text: stripInline(bullet[1]!) });
      continue;
    }

    const numbered = /^\s*\d+\.\s+(.*)$/.exec(line);
    if (numbered) {
      blocks.push({ kind: 'bullet', text: stripInline(numbered[1]!) });
      continue;
    }

    if (line.trim() === '---') {
      blocks.push({ kind: 'spacer' });
      continue;
    }

    blocks.push({ kind: 'paragraph', text: stripInline(line.trim()) });
  }

  return blocks;
}

function stripInline(text: string): string {
  return text
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/<[^>]+>/g, '')
    .trim();
}

function xmlEscape(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/** Build the .docx bytes. */
function buildDocx(blocks: readonly DocxBlock[]): Uint8Array {
  const paragraphs = blocks.map((block) => renderParagraph(block)).join('');

  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
<w:body>
${paragraphs}
<w:sectPr>
  <w:pgSz w:w="11906" w:h="16838"/>
  <w:pgMar w:top="1418" w:right="1418" w:bottom="1418" w:left="1418" w:header="708" w:footer="708" w:gutter="0"/>
</w:sectPr>
</w:body>
</w:document>`;

  const stylesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
<w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri" w:cs="Calibri"/><w:sz w:val="22"/></w:rPr></w:rPrDefault></w:docDefaults>
<w:style w:type="paragraph" w:styleId="Normal" w:default="1"><w:name w:val="Normal"/><w:pPr><w:spacing w:after="120" w:line="276" w:lineRule="auto"/></w:pPr></w:style>
<w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:pPr><w:spacing w:before="0" w:after="240"/></w:pPr><w:rPr><w:b/><w:sz w:val="48"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="Subtitle"><w:name w:val="Subtitle"/><w:basedOn w:val="Normal"/><w:rPr><w:color w:val="595959"/><w:sz w:val="24"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:pPr><w:outlineLvl w:val="0"/><w:spacing w:before="360" w:after="120"/></w:pPr><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:basedOn w:val="Normal"/><w:pPr><w:outlineLvl w:val="1"/><w:spacing w:before="280" w:after="100"/></w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="Heading3"><w:name w:val="heading 3"/><w:basedOn w:val="Normal"/><w:pPr><w:outlineLvl w:val="2"/><w:spacing w:before="220" w:after="80"/></w:pPr><w:rPr><w:b/><w:sz w:val="24"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="ListParagraph"><w:name w:val="List Paragraph"/><w:basedOn w:val="Normal"/><w:pPr><w:ind w:left="360"/><w:spacing w:after="60"/></w:pPr></w:style>
</w:styles>`;

  const contentTypes = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
<Default Extension="xml" ContentType="application/xml"/>
<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
</Types>`;

  const rootRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
</Relationships>`;

  const docRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>`;

  const coreXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<dc:title>Compliance Documentation Pack</dc:title>
<dc:creator>ShipReady</dc:creator>
<cp:lastModifiedBy>ShipReady</cp:lastModifiedBy>
<dcterms:created xsi:type="dcterms:W3CDTF">${new Date().toISOString()}</dcterms:created>
</cp:coreProperties>`;

  return zipSync([
    { name: '[Content_Types].xml', data: contentTypes },
    { name: '_rels/.rels', data: rootRels },
    { name: 'docProps/core.xml', data: coreXml },
    { name: 'word/document.xml', data: documentXml },
    { name: 'word/_rels/document.xml.rels', data: docRels },
    { name: 'word/styles.xml', data: stylesXml },
  ]);
}

function renderParagraph(block: DocxBlock): string {
  switch (block.kind) {
    case 'pageBreak':
      return '<w:p><w:r><w:br w:type="page"/></w:r></w:p>';
    case 'spacer':
      return '<w:p/>';
    case 'title':
      return `<w:p><w:pPr><w:pStyle w:val="Title"/></w:pPr><w:r><w:t xml:space="preserve">${xmlEscape(block.text)}</w:t></w:r></w:p>`;
    case 'subtitle':
      return `<w:p><w:pPr><w:pStyle w:val="Subtitle"/></w:pPr><w:r><w:t xml:space="preserve">${xmlEscape(block.text)}</w:t></w:r></w:p>`;
    case 'heading':
      return `<w:p><w:pPr><w:pStyle w:val="Heading${block.level}"/></w:pPr><w:r><w:t xml:space="preserve">${xmlEscape(block.text)}</w:t></w:r></w:p>`;
    case 'bullet':
      return `<w:p><w:pPr><w:pStyle w:val="ListParagraph"/></w:pPr><w:r><w:t xml:space="preserve">• ${xmlEscape(block.text)}</w:t></w:r></w:p>`;
    default:
      return `<w:p><w:pPr><w:pStyle w:val="Normal"/></w:pPr><w:r><w:t xml:space="preserve">${xmlEscape(block.text)}</w:t></w:r></w:p>`;
  }
}

// ---------------------------------------------------------------------------
// ZIP writer (store, no compression)
//
// A .docx with stored entries opens correctly everywhere: Word, LibreOffice,
// Google Docs and every unzip implementation. Compressing would need a deflate
// implementation, and the saving is a few kilobytes on a document this shape.
// ---------------------------------------------------------------------------

interface ZipEntry {
  name: string;
  data: string;
}

export function zipSync(entries: readonly ZipEntry[]): Uint8Array {
  const encoder = new TextEncoder();
  const chunks: Uint8Array[] = [];
  const central: Uint8Array[] = [];
  let offset = 0;

  for (const entry of entries) {
    const nameBytes = encoder.encode(entry.name);
    const dataBytes = encoder.encode(entry.data);
    const crc = crc32(dataBytes);

    const local = new Uint8Array(30 + nameBytes.length + dataBytes.length);
    const lv = new DataView(local.buffer);
    lv.setUint32(0, 0x04034b50, true); // local file header
    lv.setUint16(4, 20, true); // version needed
    lv.setUint16(6, 0, true); // flags
    lv.setUint16(8, 0, true); // method: stored
    lv.setUint16(10, 0, true); // mod time
    lv.setUint16(12, 0x2821, true); // mod date (2000-01-01, deterministic)
    lv.setUint32(14, crc, true);
    lv.setUint32(18, dataBytes.length, true);
    lv.setUint32(22, dataBytes.length, true);
    lv.setUint16(26, nameBytes.length, true);
    lv.setUint16(28, 0, true);
    local.set(nameBytes, 30);
    local.set(dataBytes, 30 + nameBytes.length);
    chunks.push(local);

    const cd = new Uint8Array(46 + nameBytes.length);
    const cv = new DataView(cd.buffer);
    cv.setUint32(0, 0x02014b50, true); // central directory header
    cv.setUint16(4, 20, true);
    cv.setUint16(6, 20, true);
    cv.setUint16(8, 0, true);
    cv.setUint16(10, 0, true);
    cv.setUint16(12, 0, true);
    cv.setUint16(14, 0x2821, true);
    cv.setUint32(16, crc, true);
    cv.setUint32(20, dataBytes.length, true);
    cv.setUint32(24, dataBytes.length, true);
    cv.setUint16(28, nameBytes.length, true);
    cv.setUint32(42, offset, true);
    cd.set(nameBytes, 46);
    central.push(cd);

    offset += local.length;
  }

  const centralSize = central.reduce((sum, c) => sum + c.length, 0);
  const end = new Uint8Array(22);
  const ev = new DataView(end.buffer);
  ev.setUint32(0, 0x06054b50, true); // end of central directory
  ev.setUint16(8, entries.length, true);
  ev.setUint16(10, entries.length, true);
  ev.setUint32(12, centralSize, true);
  ev.setUint32(16, offset, true);

  const total = offset + centralSize + end.length;
  const out = new Uint8Array(total);
  let cursor = 0;
  for (const chunk of [...chunks, ...central, end]) {
    out.set(chunk, cursor);
    cursor += chunk.length;
  }
  return out;
}

function crc32(data: Uint8Array): number {
  let crc = 0xffffffff;
  for (let i = 0; i < data.length; i++) {
    crc ^= data[i]!;
    for (let bit = 0; bit < 8; bit++) {
      crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1;
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}